import { Service } from '@/types';

export const services: Service[] = [
  {
    id: '1',
    title: 'Superbonus 110%',
    description: 'Gestione e cessione del Superbonus 110% per interventi di efficientamento energetico e antisismici.',
    icon: 'home',
    route: '/services/superbonus-110',
    percentage: 87,
    maxAmount: 96000,
  },
  {
    id: '2',
    title: 'Bonus Edilizi',
    description: 'Cessione di crediti per bonus ristrutturazioni, ecobonus e altri incentivi edilizi.',
    icon: 'hammer',
    route: '/services/bonus-edilizi',
    percentage: 85,
    maxAmount: 48000,
  },
  {
    id: '3',
    title: 'Crediti Industria 4.0',
    description: 'Gestione crediti per investimenti in beni strumentali e tecnologie innovative.',
    icon: 'cpu',
    route: '/services/industria-4-0',
    percentage: 80,
    maxAmount: 2500000,
  },
  {
    id: '4',
    title: 'Credito IVA',
    description: 'Cessione e monetizzazione dei crediti IVA per migliorare il cash flow aziendale.',
    icon: 'receipt',
    route: '/services/credito-iva',
    percentage: 75,
  },
  {
    id: '5',
    title: 'Crediti PIA',
    description: 'Gestione crediti del Piano Industria Avanzata per investimenti in ricerca e sviluppo.',
    icon: 'flask',
    route: '/services/crediti-pia',
    percentage: 78,
    maxAmount: 1000000,
  },
  {
    id: '6',
    title: 'Crediti DTA',
    description: 'Conversione e gestione delle Deferred Tax Assets per ottimizzazione fiscale.',
    icon: 'file-text',
    route: '/services/crediti-dta',
    percentage: 70,
    maxAmount: 500000,
  },
];